api_platform:
    eager_loading:
        max_joins: 5
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
